// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0GYDsxcNwHERG5PUq_4H4WzTsTmqu6o',
    appId: '1:721018073572:web:2d835c18e3a84ea353d7f1',
    messagingSenderId: '721018073572',
    projectId: 'sprint2-icuisine-project',
    authDomain: 'sprint2-icuisine-project.firebaseapp.com',
    storageBucket: 'sprint2-icuisine-project.firebasestorage.app',
    measurementId: 'G-627LXVXGNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD0SnZGKy4oEsK_TGwWz4E8g3bBGi3vwc',
    appId: '1:721018073572:android:12144f901bea9aa853d7f1',
    messagingSenderId: '721018073572',
    projectId: 'sprint2-icuisine-project',
    storageBucket: 'sprint2-icuisine-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVGBhBydVecsvpuYuHPYppdksBX7vaQE',
    appId: '1:721018073572:ios:279f4303a4bbfee553d7f1',
    messagingSenderId: '721018073572',
    projectId: 'sprint2-icuisine-project',
    storageBucket: 'sprint2-icuisine-project.firebasestorage.app',
    iosClientId: '721018073572-1bn0g7c4s158r4t5oharub7g2aa0bfpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.icuisine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVGBhBydVecsvpuYuHPYppdksBX7vaQE',
    appId: '1:721018073572:ios:279f4303a4bbfee553d7f1',
    messagingSenderId: '721018073572',
    projectId: 'sprint2-icuisine-project',
    storageBucket: 'sprint2-icuisine-project.firebasestorage.app',
    iosClientId: '721018073572-1bn0g7c4s158r4t5oharub7g2aa0bfpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.icuisine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx0GYDsxcNwHERG5PUq_4H4WzTsTmqu6o',
    appId: '1:721018073572:web:4ef2b989c499ba1353d7f1',
    messagingSenderId: '721018073572',
    projectId: 'sprint2-icuisine-project',
    authDomain: 'sprint2-icuisine-project.firebaseapp.com',
    storageBucket: 'sprint2-icuisine-project.firebasestorage.app',
    measurementId: 'G-9X3B0VWSK9',
  );

}