// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_rtmIFgy3AB7KfCuM1TPAMw2MyZo8Yrk',
    appId: '1:232472544702:web:9d49715c7fbd74142365ef',
    messagingSenderId: '232472544702',
    projectId: 'icuisine-41831',
    authDomain: 'icuisine-41831.firebaseapp.com',
    storageBucket: 'icuisine-41831.firebasestorage.app',
    measurementId: 'G-WTJ8X0SWYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQx2CQX1Y-lcLxk18aPfU-qlFuCDkvh-8',
    appId: '1:232472544702:android:e02efef291c1615f2365ef',
    messagingSenderId: '232472544702',
    projectId: 'icuisine-41831',
    storageBucket: 'icuisine-41831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdbs81zraC-Tjej1Y8c4-OC24aRTr78o',
    appId: '1:232472544702:ios:195fac5a4d5089382365ef',
    messagingSenderId: '232472544702',
    projectId: 'icuisine-41831',
    storageBucket: 'icuisine-41831.firebasestorage.app',
    iosBundleId: 'com.example.icuisine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZdbs81zraC-Tjej1Y8c4-OC24aRTr78o',
    appId: '1:232472544702:ios:195fac5a4d5089382365ef',
    messagingSenderId: '232472544702',
    projectId: 'icuisine-41831',
    storageBucket: 'icuisine-41831.firebasestorage.app',
    iosBundleId: 'com.example.icuisine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_rtmIFgy3AB7KfCuM1TPAMw2MyZo8Yrk',
    appId: '1:232472544702:web:19d4ff5f6fe754ef2365ef',
    messagingSenderId: '232472544702',
    projectId: 'icuisine-41831',
    authDomain: 'icuisine-41831.firebaseapp.com',
    storageBucket: 'icuisine-41831.firebasestorage.app',
    measurementId: 'G-JNB7J7F6C7',
  );

}